{
  "swagger": "2.0",
  "info": {
    "title": "OneDriveClient",
    "description": "OneDrive Client for Testing Webhook demo",
    "version": "1.0",
    "contact": {
      "name": "Nirmal",
      "url": "https://nkdews.me",
      "email": "nirmalk.web@gmail.com"
    }
  },
  "host": "graph.microsoft.com",
  "basePath": "/v1.0",
  "schemes": [
    "https"
  ],
  "paths": {
    "/subscriptions-list": {
      "get": {
        "summary": "GetSubscriptions",
        "description": "GetSubscriptions",
        "operationId": "GetSubscriptions"
      }
    },
    "/subscriptions": {
      "post": {
        "summary": "OnFileChanged",
        "description": "OnFileChanged",
        "operationId": "OnFileChanged"
      }
    },
    "/me/drive/root/delta": {
      "get": {
        "summary": "deltafiles",
        "description": "deltaFiles",
        "operationId": "GetDelatFiles"
      }
    },
    "/subscriptions/{subId}": {
      "get": {
        "summary": "GetSubscription",
        "description": "GetSubscription",
        "operationId": "GetSubscription"
      }
    },
    "/subscriptions('{subId}')": {
      "delete": {
        "summary": "Delete Webhook",
        "description": "DeleteWebhook",
        "operationId": "DeleteWebhook"
      }
    }
  },
  "securityDefinitions": {
    "undefined": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://login.live.com/oauth20_authorize.srf",
      "tokenUrl": "https://login.live.com/oauth20_token.srf",
      "scopes": {
        "Files.Read": "Files.Read",
        "Files.ReadWrite": "Files.ReadWrite",
        "Files.Read.All": "Files.Read.All",
        "Files.ReadWrite.All": "Files.ReadWrite.All",
        "offline_access": "offline_access"
      }
    }
  },
  "security": [
    {
      "undefined": [
        "Files.Read",
        "Files.ReadWrite",
        "Files.Read.All",
        "Files.ReadWrite.All",
        "offline_access"
      ]
    }
  ],
  "tags": []
}